apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: k10
    meta.helm.sh/release-namespace: kasten-io
    volume.beta.kubernetes.io/storage-provisioner: cinder.csi.openstack.org
    volume.kubernetes.io/storage-provisioner: cinder.csi.openstack.org
  creationTimestamp: "2024-09-11T07:00:17Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: k10
    app.kubernetes.io/instance: k10
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k10
    component: catalog
    helm.sh/chart: k10-7.0.8
    heritage: Helm
    release: k10
  name: catalog-pv-claim
  namespace: kasten-io
  resourceVersion: "41653164949"
  uid: 1016df1b-6b8b-4922-94ad-6a023f43f3e3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 
  storageClassName: csi-cinder-high-speed
  volumeMode: Filesystem
status:
  phase: Pending
