apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-staging
  namespace: staging
  labels:
    app: webapp-staging
spec:
  selector:
    matchLabels:
      app: webapp-staging
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp-staging
    spec:
      containers:
      - name: web-backend
        image: thetiptopymcm/thetiptop-backend:test
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1Gi
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret-staging
              key: mysql-user
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-staging
              key: mysql-password
        - name: DATABASE_URL
          value: "mysql://thetiptop:thetiptop2024@mysql-service.default.svc.cluster.local:3306/thetiptop"
        - name: RESENd_API_KEY
          value: "re_4Ft1Hm5s_C3s5tT4ZD75krrY7mC7ZuQnC"
        ports:
        - containerPort: 3000
          name: webapp

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-lb-staging
  namespace: staging
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  #   service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-12345678,eipalloc-87654321"

spec:
  selector:
    app: webapp-staging
  type: LoadBalancer
  ports:
  - name: webapp
    protocol: TCP
    port: 3000
    targetPort: 3001
