# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-staging
  namespace: staging
type: Opaque
data:
  mysql-user: dGhldGlwdG9w
  mysql-password: dGhldGlwdG9wMjAyNA==
  ROOT_PASSWORD: cm9vdA==
