apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - name: webapp
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30200
