apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-new-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: retained
  hostPath:
    path: /mnt/data/mysql-new
