apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-jenkins-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: new-retained
