apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2  # Ajustez le nombre de réplicas selon vos besoins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: thetiptopymcm/thetiptop-frontend:latest
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 500Mi
        ports:
        - containerPort: 3000
          name: frontend

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: default
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80         
    targetPort: 3000
