apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: thetiptopymcm/thetiptop-frontend:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 500Mi
        ports:
        - containerPort: 3000
          name: frontend
        env:
        - name: NODE_ENV
          value: "production"
        - name: AUTH_SECRET
          value: "mSaxQBtqqQbdhBoCFnHMLxNLmPzb0DaiMInMkbmeZkg="
        - name: AUTH_URL
          value: "https://dsp5-archi-022a-4-5-g2.fr"  
        - name: AUTH_TRUST_HOST
          value: "true"  
        - name: DATABASE_URL
          value: "mysql://thetiptop:thetiptop2024@mysql-service:3306/thetiptop"  
        

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: default
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80         
    targetPort: 3000
