apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-certificate
  namespace: default
spec:
  secretName: my-certificate-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dsp5-archi-022a-4-5-g2.fr
  dnsNames:
    - dsp5-archi-022a-4-5-g2.fr
