apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildcard-subdomain-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: "*.dsp5-archi-022a-4-5-g2.fr"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-lb
            port:
              number: 80
  tls:
  - hosts:
    - "*.dsp5-archi-022a-4-5-g2.fr"
    secretName: wildcard-cert-hcrz5
