apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redirect-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - www.dsp5-archi-022a-4-5-g2.fr
    - dsp5-archi-022a-4-5-g2.fr
    secretName: front-tls
  rules:
  - host: www.dsp5-archi-022a-4-5-g2.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-lb
            port:
              number: 80
  - host: dsp5-archi-022a-4-5-g2.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-lb
            port:
              number: 80
