apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-home-pv-new
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: retained
  hostPath:
    path: "/mnt/data/jenkins-new"
