apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-jenkins-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: my-storage-class
