apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-pre-prod
  namespace: pre-prod
  labels:
    app: webapp-pre-prod
spec:
  selector:
    matchLabels:
      app: webapp-pre-prod
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp-pre-prod
    spec:
      containers:
      - name: web-backend
        image: thetiptopymcm/thetiptop-backend:latest
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1Gi
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret-pre-prod
              key: mysql-user
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-pre-prod
              key: mysql-password
        - name: DATABASE_URL
          value: "mysql://thetiptop:thetiptop2024@mysql-service.default.svc.cluster.local:3306/thetiptop"
        ports:
        - containerPort: 3000
          name: webapp

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-lb-pre-prod
  namespace: pre-prod
spec:
  selector:
    app: webapp-pre-prod
  type: LoadBalancer
  ports:
  - name: webapp
    protocol: TCP
    port: 3000
    targetPort: 3001
