apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-pre-prod-deployment
  namespace: front-pre-prod
  labels:
    app: frontend
    environment: pre-prod
spec:
  selector:
    matchLabels:
      app: frontend
      environment: pre-prod
  replicas: 1 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
        environment: pre-prod
    spec:
      containers:
      - name: frontend
        image: thetiptopymcm/thetiptop-frontend:latest
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 500Mi
        ports:
        - containerPort: 3000
          name: frontend
        env:
        - name: NODE_ENV
          value: "staging"
        - name: AUTH_SECRET
          value: "mSaxQBtqqQbdhBoCFnHMLxNLmPzb0DaiMInMkbmeZkg="  # Remplacez par votre secret sécurisé
        - name: AUTH_URL
          value: "http://51.91.81.95"  
        - name: AUTH_TRUST_HOST
          value: "true"  
        - name: DATABASE_URL
          value: "mysql://thetiptop:thetiptop2024@mysql-service:3306/thetiptop"  

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-pre-prod-lb
  namespace: front-pre-prod
spec:
  selector:
    app: frontend
    environment: pre-prod
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80         
    targetPort: 3000
